### ISSUE TITLE
Add support for SSR

### ISSUE THREAD

**Issue by jonkoops** [Amsterdam/matomo-tracker#140]
In order to make sure we can track page views of pages that are both server-side rendered and client-side rendered we need to come up with a plan to allow our code to run in both environments.

**Comment by daphnesmit** [comment]
I was actually coincidentally 5 minutes ago also trying to use your pkg in a nextjs app!
I ran into the same issue.
I was thinking you could send the setting from the createInstance to the provider, add a useeffect there and initialize the instance since useEffect is only run clientside. But I am not sure if that is the prefered solution. 
Maybe you could just initialize the script in a dangerouslySetInnerHTML. Get rid of the provider and only let the library be a useMatomo hook. The hook would just check for the  matomo instance on the window. 
My 2 cents!

**Comment by chrisvanmook** [comment]
At least we can use the tracker in a server side environment now without reference errors: https://github.com/Amsterdam/matomo-tracker/releases/tag/v0.1.4

**Comment by jonkoops** [comment]
@chrisvanmook Should we consider this issue resolved now that we can render an application on the server successfully?

**Comment by chrisvanmook** [comment]
> @chrisvanmook Should we consider this issue resolved now that we can render an application on the server successfully?

I think we should. It doesn't support tracking on the server, however that also seems a bit pointless to support that for now, right?

**Comment by jonkoops** [comment]
Yeah agreed, I am closing this for now. If we ever do feel the need this code should work in an SSR environment including tracking we can deal with it then.
