### ISSUE TITLE
Use inside Class Components

### ISSUE THREAD

**Issue by JLyons1985** [Amsterdam/matomo-tracker#162]
I see the examples with how to use this package with hooks and function components. I try to do the same thing inside class based components and no luck. Is there a way to do this inside React Class Components? If not, what are the chances of this being included?

**Comment by jonkoops** [comment]
Hi @JLyons1985, according to the [React documentation](https://reactjs.org/docs/hooks-faq.html#should-i-use-hooks-classes-or-a-mix-of-both
) it is not possible to use hooks in class components:

> You can’t use Hooks _inside_ a class component, but you can definitely mix classes and function components with Hooks in a single tree. Whether a component is a class or a function that uses Hooks is an implementation detail of that component. In the longer term, we expect Hooks to be the primary way people write React components.

Since the React team has expressed that Hooks will be the primary way of writing React components going forwards we have chosen not to support class style components.

**Comment by exinferis** [comment]
Since both class based components and function components are equally supported by react and larger projects tend to strongly favour class based components this should be considered to be reopened.

**Comment by jonkoops** [comment]
> Since both class based components and function components are equally supported by react and larger projects tend to strongly favour class based components this should be considered to be reopened.

We recommend you use a functional container component and pass in the methods you need to accomplish this.
